/* eslint-disable */
// This file is auto-generated. Do not edit directly.
// Extracted from HTML data-i18n attributes.
import { t } from "@lingui/core/macro";
export function _htmlTranslations() {
    // These calls exist purely so LinguiJS can extract them
    t`Dark background color`;
    t`Primary background color`;
    t`Primary outline color`;
    t`Second outline color`;
    t`Third outline color`;
    t`Focused outline color`;
    t`Primary border color`;
    t`Second border color`;
    t`Focus border color`;
    t`Second background color`;
    t`Primary hovered background color`;
    t`Second hovered background color`;
    t`Primary text color`;
    t`Second text color`;
    t`Third text color`;
    t`Third background color`;
    t`Create Theme`;
    t` - `;
    t`of`;
    t` - `;
    t`-Select File-`;
    t`Search mode`;
    t`Search everywhere`;
    t`Search only in source text`;
    t`Search only in translation`;
    t`Select column`;
    t`Rightmost filled`;
    t`Select files (You can hold LMB and drag to select multiple files)`;
    t`Context`;
    t`Use file context`;
    t`Process`;
    t`Cancel`;
    t`Select All`;
    t`Deselect All`;
    t`-Select Action-`;
    t`Trim`;
    t`Translate`;
    t`Wrap`;
    t`-Select Column-`;
    t`Create Theme`;
    t`Select Output Path`;
    t`Skip files:`;
    t`Skip maps:`;
    t`Skip events:`;
    t`Write`;
    t`How to read files.`;
    t`How to handle duplicates in text.`;
    t`Remove duplicates`;
    t`Allow duplicates`;
    t`Romanize: If you parsing text from a Japanese game, that contains symbols like 「」, which are just the Japanese quotation marks, it automatically replaces these symbols by their western equivalents (in this case, '').`;
    t`Trim: Removes the leading and trailing whitespace from extracted strings. Don't use this option unless you know that trimming the text won't cause any incorrect behavior`;
    t`Disable Custom Processing: Disables built-in custom processing, implemented for some games. Right now, implemented for the following titles: LISA: The Painful and its derivatives, Fear & Hunger 2: Termina. Will be automatically set if it was used in read`;
    t`Ignore: Ignore entries from .rvpacker-ignore file`;
    t`Skip files:`;
    t`Skip maps:`;
    t`Skip events:`;
    t`Parse event metadata from maps`;
    t`Read`;
    t`Skip files:`;
    t`Skip maps:`;
    t`Skip events:`;
    t`Create .rvpacker-ignore file from purged lines to prevent their further appearance`;
    t`Purge`;
    t`Glossary`;
    t`Match Menu`;
    t`Check only current file`;
    t`Source`;
    t`Translation`;
    t`Note`;
    t`File`;
    t`Line`;
    t`Term`;
    t`Result`;
    t`Info`;
    t`Tabs (Tab)`;
    t`Save (Ctrl + S)`;
    t`Write (Alt + C)`;
    t`Open directory`;
    t`Settings`;
    t`Themes`;
    t`Bookmarks (Ctrl + B)`;
    t`Search (Ctrl + F)`;
    t`Batch menu`;
    t`Read menu`;
    t`Purge menu`;
    t`Glossary`;
    t`Search`;
    t`Replace all matches`;
    t`Put text to translation textarea of matching source text`;
    t`Consider case (Alt + C)`;
    t`Search the whole text (Alt + W)`;
    t`Search by regular expressions (Alt + R)`;
    t`Search only in current tab (Alt + L)`;
    t`Theme name. Allowed characters: a-z, A-Z, 0-9, -, _.`;
    t`Search input`;
    t`Replace input`;
    t`Define a context, surrounding selected files. It might be better to use filenames explicitly, like 'a happens before map256', or something like that.`;
    t`Line length for wrapping`;
    t`Map indices, e.g. 5,30,18...`;
    t`Event indices, e.g. 5,30,18...`;
    t`Map indices, e.g. 5,30,18...`;
    t`Event indices, e.g. 5,30,18...`;
    t`Map indices, e.g. 5,30,18...`;
    t`Event indices, e.g. 5,30,18...`;
}