/* eslint-disable */
// This file is auto-generated. Do not edit directly.
// Extracted from HTML data-i18n attributes.
import { t } from "@lingui/core/macro";
export function _htmlTranslations() {
    // These calls exist purely so LinguiJS can extract them
    t`File`;
    t`Help`;
    t`Language`;
    t`Reload (F5)`;
    t`Help`;
    t`About`;
    t`Dark background color`;
    t`Primary background color`;
    t`Primary outline color`;
    t`Second outline color`;
    t`Third outline color`;
    t`Focused outline color`;
    t`Primary border color`;
    t`Second border color`;
    t`Focus border color`;
    t`Second background color`;
    t`Primary hovered background color`;
    t`Second hovered background color`;
    t`Primary text color`;
    t`Second text color`;
    t`Third text color`;
    t`Third background color`;
    t`Create theme`;
    t` - `;
    t`of`;
    t` - `;
    t`Search mode`;
    t`Search everywhere`;
    t`Search only in source text`;
    t`Search only in translation`;
    t`Select column`;
    t`Rightmost filled`;
    t`Select files (You can hold LMB and drag to select multiple files)`;
    t`Select All`;
    t`Deselect All`;
    t`Apply`;
    t`Cancel`;
    t`-Select Action-`;
    t`Trim`;
    t`Translate`;
    t`Wrap`;
    t`-Select Column-`;
    t`Create Theme`;
    t`Select Output Path`;
    t`Disable Mapxxx processing`;
    t`Disable Actors, Armors, Troops etc. processing`;
    t`Disable System processing`;
    t`Disable plugins.js/Scripts processing`;
    t`Apply`;
    t`Read mode:`;
    t`Append`;
    t`Force rewrite`;
    t`In case, when the game text you've parsed updates, or the GUI update, it makes sense to re-read files in this mode, to append new text to existing translation without overwriting the progress. Before reading ensure you've saved the translation!`;
    t`Duplicate mode`;
    t`Allow duplicates`;
    t`Remove duplicates`;
    t`Whether to romanize text.`;
    t`Disable custom processing`;
    t`Disable Mapxxx processing`;
    t`Disable Actors, Armors, Troops etc. processing`;
    t`Disable System processing`;
    t`Disable plugins.js/Scripts processing`;
    t`Ignore entries from .rvpacker-ignore file`;
    t`Remove the leading and trailing whitespace from extracted strings. Could lead to non-working or incorrect text writing.`;
    t`Read`;
    t`Disable Mapxxx processing`;
    t`Disable Actors, Armors, Troops etc. processing`;
    t`Disable System processing`;
    t`Disable plugins.js/Scripts processing`;
    t`Create .rvpacker-ignore file from purged lines to prevent their further appearance`;
    t`Purge`;
    t`Tabs (Tab)`;
    t`Save (Ctrl + S)`;
    t`Write (Alt + C)`;
    t`Open directory`;
    t`Settings`;
    t`Themes`;
    t`Bookmarks (Ctrl + B)`;
    t`Search (Ctrl + F)`;
    t`Batch menu`;
    t`Read menu`;
    t`Purge menu`;
    t`Search`;
    t`Replace all matches`;
    t`Put text to translation textarea of matching source text`;
    t`Consider case (Alt + C)`;
    t`Search the whole text (Alt + W)`;
    t`Search by regular expressions (Alt + R)`;
    t`Search only in current tab (Alt + L)`;
    t`Machine translation from language (e. g. en, ru-RU)`;
    t`Machine translation to language (e. g. en, ru-RU)`;
    t`Theme name. Allowed characters: a-z, A-Z, 0-9, -, _.`;
    t`Search input`;
    t`Replace input`;
}